### ISSUE TITLE
Research questions to guide rustc_ast integration

### ISSUE THREAD

**Issue by connorkuehl** [nordzilla/cargo-doc-gen#2]
Answer the following questions:

- [ ] How can we invoke rustc_ast from our crate?
- [ ] Do the AST nodes come bundled with their respective source code locations? (Used for injecting template info)
- [ ] Can we extract full module paths from referenced decls (modules, structs, etc)? Important for linking docs.

**Comment by connorkuehl** [comment]
If we're unable to consume the rustc_ast crate directly, we might be able to shell out to `rustc` and tell it to dump the AST to JSON:

```console
$ rustc +nightly -Z ast-json src/main.rs﻿
```

**Comment by nordzilla** [comment]
It looks like Clippy has a module for extracting information from `rustc_ast`. We could probably learn a lot from this and potentially base what we need off of this example.

https://github.com/rust-lang/rust-clippy/blob/master/clippy_utils/src/ast_utils.rs

**Comment by squidboylan** [comment]
We probably want to use `syn` https://docs.rs/syn/1.0.69/syn/index.html , it should be able to parse rust code and give us an AST, it might not have everything we need but should get us most of the way there.

**Comment by squidboylan** [comment]
Looks like syn parses doc comments as attributes to Items so we should be able to just consume each item and figure out if it needs to have doc comments and then read the literal doc comment out of its attributes.

**Comment by nordzilla** [comment]
Conclusion 2021-04-17:

We have decided to use [syn](https://crates.io/crates/syn) to parse the Rust code into an AST.
